-- =====================================================
-- 为 order_system.sql 中的表添加中文注释
-- =====================================================

-- 1. packages 表注释
ALTER TABLE `packages` COMMENT = 'AI积分套餐表';

-- packages 表字段注释
ALTER TABLE `packages` 
MODIFY COLUMN `id` CHAR(36) NOT NULL COMMENT '套餐唯一标识ID',
MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '套餐名称',
MODIFY COLUMN `name_en` VARCHAR(100) NULL COMMENT '套餐英文名称',
MODIFY COLUMN `version` VARCHAR(20) NOT NULL COMMENT '套餐版本号',
MODIFY COLUMN `description` TEXT NULL COMMENT '套餐描述',
MODIFY COLUMN `price` INT NOT NULL COMMENT '套餐价格(分)',
MODIFY COLUMN `original_price` INT NULL COMMENT '原价(分)',
MODIFY COLUMN `currency` VARCHAR(10) NOT NULL DEFAULT 'CNY' COMMENT '货币类型',
MODIFY COLUMN `daily_credits` INT NOT NULL COMMENT '每日积分额度',
MODIFY COLUMN `valid_days` INT NOT NULL DEFAULT 30 COMMENT '有效天数',
MODIFY COLUMN `features` JSON NULL COMMENT '套餐特性(JSON格式)',
MODIFY COLUMN `limitations` JSON NULL COMMENT '套餐限制(JSON格式)',
MODIFY COLUMN `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序顺序',
MODIFY COLUMN `is_active` BOOLEAN NOT NULL DEFAULT true COMMENT '是否激活',
MODIFY COLUMN `is_recommended` BOOLEAN NOT NULL DEFAULT false COMMENT '是否推荐',
MODIFY COLUMN `tag` VARCHAR(50) NULL COMMENT '标签(如HOT、NEW等)',
MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

-- 2. user_packages 表注释
ALTER TABLE `user_packages` COMMENT = '用户套餐订阅表';

-- user_packages 表字段注释
ALTER TABLE `user_packages`
MODIFY COLUMN `id` CHAR(36) NOT NULL COMMENT '记录唯一标识ID',
MODIFY COLUMN `user_uuid` VARCHAR(255) NOT NULL COMMENT '用户UUID',
MODIFY COLUMN `package_id` CHAR(36) NOT NULL COMMENT '套餐ID',
MODIFY COLUMN `order_no` VARCHAR(255) NOT NULL COMMENT '订单号',
MODIFY COLUMN `start_date` DATETIME(3) NOT NULL COMMENT '套餐开始日期',
MODIFY COLUMN `end_date` DATETIME(3) NOT NULL COMMENT '套餐结束日期',
MODIFY COLUMN `daily_credits` INT NOT NULL COMMENT '每日积分额度',
MODIFY COLUMN `package_snapshot` JSON NULL COMMENT '套餐快照(购买时的套餐信息)',
MODIFY COLUMN `is_active` BOOLEAN NOT NULL DEFAULT true COMMENT '是否激活',
MODIFY COLUMN `is_auto_renew` BOOLEAN NOT NULL DEFAULT false COMMENT '是否自动续费',
MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

-- 3. credit_balances 表注释
ALTER TABLE `credit_balances` COMMENT = '用户积分余额表';

-- credit_balances 表字段注释
ALTER TABLE `credit_balances`
MODIFY COLUMN `id` CHAR(36) NOT NULL COMMENT '记录唯一标识ID',
MODIFY COLUMN `user_uuid` VARCHAR(255) NOT NULL COMMENT '用户UUID',
MODIFY COLUMN `package_credits` INT NOT NULL DEFAULT 0 COMMENT '套餐积分余额',
MODIFY COLUMN `package_reset_at` DATETIME(3) NULL COMMENT '套餐积分重置时间',
MODIFY COLUMN `independent_credits` INT NOT NULL DEFAULT 0 COMMENT '独立积分余额(购买的额外积分)',
MODIFY COLUMN `total_used` INT NOT NULL DEFAULT 0 COMMENT '累计使用积分',
MODIFY COLUMN `total_purchased` INT NOT NULL DEFAULT 0 COMMENT '累计购买积分',
MODIFY COLUMN `version` INT NOT NULL DEFAULT 0 COMMENT '版本号(乐观锁)',
MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

-- 4. credit_transactions 表注释
ALTER TABLE `credit_transactions` COMMENT = '积分流水记录表';

-- credit_transactions 表字段注释
ALTER TABLE `credit_transactions`
MODIFY COLUMN `id` CHAR(36) NOT NULL COMMENT '记录唯一标识ID',
MODIFY COLUMN `trans_no` VARCHAR(255) NOT NULL COMMENT '交易流水号',
MODIFY COLUMN `user_uuid` VARCHAR(255) NOT NULL COMMENT '用户UUID',
MODIFY COLUMN `type` VARCHAR(20) NOT NULL COMMENT '交易类型(income收入/expense支出/reset重置)',
MODIFY COLUMN `credit_type` VARCHAR(20) NOT NULL COMMENT '积分类型(package套餐积分/independent独立积分)',
MODIFY COLUMN `amount` INT NOT NULL COMMENT '交易金额',
MODIFY COLUMN `before_balance` INT NOT NULL COMMENT '交易前余额',
MODIFY COLUMN `after_balance` INT NOT NULL COMMENT '交易后余额',
MODIFY COLUMN `order_no` VARCHAR(255) NULL COMMENT '关联订单号',
MODIFY COLUMN `description` VARCHAR(500) NULL COMMENT '交易描述',
MODIFY COLUMN `metadata` JSON NULL COMMENT '元数据(JSON格式)',
MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

-- 5. orders 表新增字段注释
ALTER TABLE `orders`
MODIFY COLUMN `order_type` VARCHAR(20) NOT NULL DEFAULT 'credits' COMMENT '订单类型(package套餐/credits积分)',
MODIFY COLUMN `package_id` CHAR(36) NULL COMMENT '套餐ID',
MODIFY COLUMN `package_snapshot` JSON NULL COMMENT '套餐快照(购买时的套餐信息)',
MODIFY COLUMN `credit_amount` INT NULL COMMENT '积分数量',
MODIFY COLUMN `start_date` DATETIME(3) NULL COMMENT '套餐开始日期',
MODIFY COLUMN `end_date` DATETIME(3) NULL COMMENT '套餐结束日期',
MODIFY COLUMN `discount_amount` INT NOT NULL DEFAULT 0 COMMENT '折扣金额(分)',
MODIFY COLUMN `coupon_code` VARCHAR(50) NULL COMMENT '优惠券代码',
MODIFY COLUMN `payment_method` VARCHAR(50) NULL COMMENT '支付方式',
MODIFY COLUMN `refund_status` VARCHAR(50) NULL COMMENT '退款状态',
MODIFY COLUMN `refund_amount` INT NOT NULL DEFAULT 0 COMMENT '退款金额(分)',
MODIFY COLUMN `refund_at` DATETIME(3) NULL COMMENT '退款时间';

-- =====================================================
-- 为 mysql_init.sql 中的表添加中文注释
-- =====================================================

-- 1. users 表注释
ALTER TABLE `users` COMMENT = '用户信息表';

-- users 表字段注释
ALTER TABLE `users`
MODIFY COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '用户自增ID',
MODIFY COLUMN `uuid` VARCHAR(255) NOT NULL COMMENT '用户唯一标识UUID',
MODIFY COLUMN `email` VARCHAR(255) NOT NULL COMMENT '用户邮箱',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `nickname` VARCHAR(255) COMMENT '用户昵称',
MODIFY COLUMN `avatar_url` VARCHAR(255) COMMENT '头像URL',
MODIFY COLUMN `locale` VARCHAR(50) COMMENT '语言区域设置',
MODIFY COLUMN `signin_type` VARCHAR(50) COMMENT '登录类型',
MODIFY COLUMN `signin_ip` VARCHAR(255) COMMENT '登录IP地址',
MODIFY COLUMN `signin_provider` VARCHAR(50) COMMENT '登录提供商',
MODIFY COLUMN `signin_openid` VARCHAR(255) COMMENT '第三方登录OpenID',
MODIFY COLUMN `invite_code` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邀请码',
MODIFY COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
MODIFY COLUMN `invited_by` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邀请人UUID',
MODIFY COLUMN `is_affiliate` BOOLEAN NOT NULL DEFAULT false COMMENT '是否为推广用户',
MODIFY COLUMN `password` VARCHAR(255) COMMENT '用户密码(加密)';

-- 2. orders 表注释
ALTER TABLE `orders` COMMENT = '订单信息表';

-- orders 表字段注释
ALTER TABLE `orders`
MODIFY COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '订单自增ID',
MODIFY COLUMN `order_no` VARCHAR(255) NOT NULL COMMENT '订单号',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `user_uuid` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户UUID',
MODIFY COLUMN `user_email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户邮箱',
MODIFY COLUMN `amount` INT NOT NULL COMMENT '订单金额(分)',
MODIFY COLUMN `interval` VARCHAR(50) COMMENT '订阅周期',
MODIFY COLUMN `expired_at` DATETIME COMMENT '过期时间',
MODIFY COLUMN `status` VARCHAR(50) NOT NULL COMMENT '订单状态',
MODIFY COLUMN `stripe_session_id` VARCHAR(255) COMMENT 'Stripe会话ID',
MODIFY COLUMN `credits` INT NOT NULL COMMENT '积分数量',
MODIFY COLUMN `currency` VARCHAR(50) COMMENT '货币类型',
MODIFY COLUMN `sub_id` VARCHAR(255) COMMENT '订阅ID',
MODIFY COLUMN `sub_interval_count` INT COMMENT '订阅周期数',
MODIFY COLUMN `sub_cycle_anchor` INT COMMENT '订阅周期锚点',
MODIFY COLUMN `sub_period_end` INT COMMENT '订阅周期结束时间',
MODIFY COLUMN `sub_period_start` INT COMMENT '订阅周期开始时间',
MODIFY COLUMN `sub_times` INT COMMENT '订阅次数',
MODIFY COLUMN `product_id` VARCHAR(255) COMMENT '产品ID',
MODIFY COLUMN `product_name` VARCHAR(255) COMMENT '产品名称',
MODIFY COLUMN `valid_months` INT COMMENT '有效月数',
MODIFY COLUMN `order_detail` TEXT COMMENT '订单详情',
MODIFY COLUMN `paid_at` DATETIME COMMENT '支付时间',
MODIFY COLUMN `paid_email` VARCHAR(255) COMMENT '支付邮箱',
MODIFY COLUMN `paid_detail` TEXT COMMENT '支付详情';

-- 3. apikeys 表注释
ALTER TABLE `apikeys` COMMENT = 'API密钥表';

-- apikeys 表字段注释
ALTER TABLE `apikeys`
MODIFY COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '密钥自增ID',
MODIFY COLUMN `api_key` VARCHAR(255) NOT NULL COMMENT 'API密钥',
MODIFY COLUMN `title` VARCHAR(100) COMMENT '密钥标题',
MODIFY COLUMN `user_uuid` VARCHAR(255) NOT NULL COMMENT '用户UUID',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `status` VARCHAR(50) COMMENT '密钥状态';

-- 4. credits 表注释
ALTER TABLE `credits` COMMENT = '积分交易记录表(旧)';

-- credits 表字段注释
ALTER TABLE `credits`
MODIFY COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '记录自增ID',
MODIFY COLUMN `trans_no` VARCHAR(255) NOT NULL COMMENT '交易流水号',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `user_uuid` VARCHAR(255) NOT NULL COMMENT '用户UUID',
MODIFY COLUMN `trans_type` VARCHAR(50) NOT NULL COMMENT '交易类型',
MODIFY COLUMN `credits` INT NOT NULL COMMENT '积分数量',
MODIFY COLUMN `order_no` VARCHAR(255) COMMENT '关联订单号',
MODIFY COLUMN `expired_at` DATETIME COMMENT '过期时间';

-- 5. posts 表注释
ALTER TABLE `posts` COMMENT = '文章博客表';

-- posts 表字段注释
ALTER TABLE `posts`
MODIFY COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '文章自增ID',
MODIFY COLUMN `uuid` VARCHAR(255) NOT NULL COMMENT '文章UUID',
MODIFY COLUMN `slug` VARCHAR(255) COMMENT 'URL别名',
MODIFY COLUMN `title` VARCHAR(255) COMMENT '文章标题',
MODIFY COLUMN `description` TEXT COMMENT '文章描述',
MODIFY COLUMN `content` TEXT COMMENT '文章内容',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
MODIFY COLUMN `status` VARCHAR(50) COMMENT '文章状态',
MODIFY COLUMN `cover_url` VARCHAR(255) COMMENT '封面图URL',
MODIFY COLUMN `author_name` VARCHAR(255) COMMENT '作者名称',
MODIFY COLUMN `author_avatar_url` VARCHAR(255) COMMENT '作者头像URL',
MODIFY COLUMN `locale` VARCHAR(50) COMMENT '语言区域';

-- 6. affiliates 表注释
ALTER TABLE `affiliates` COMMENT = '推广联盟表';

-- affiliates 表字段注释
ALTER TABLE `affiliates`
MODIFY COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '记录自增ID',
MODIFY COLUMN `user_uuid` VARCHAR(255) NOT NULL COMMENT '用户UUID',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `status` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '状态',
MODIFY COLUMN `invited_by` VARCHAR(255) NOT NULL COMMENT '邀请人UUID',
MODIFY COLUMN `paid_order_no` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '支付订单号',
MODIFY COLUMN `paid_amount` INT NOT NULL DEFAULT 0 COMMENT '支付金额(分)',
MODIFY COLUMN `reward_percent` INT NOT NULL DEFAULT 0 COMMENT '奖励比例',
MODIFY COLUMN `reward_amount` INT NOT NULL DEFAULT 0 COMMENT '奖励金额(分)';

-- 7. feedbacks 表注释
ALTER TABLE `feedbacks` COMMENT = '用户反馈表';

-- feedbacks 表字段注释
ALTER TABLE `feedbacks`
MODIFY COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '反馈自增ID',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `status` VARCHAR(50) COMMENT '反馈状态',
MODIFY COLUMN `user_uuid` VARCHAR(255) COMMENT '用户UUID',
MODIFY COLUMN `content` TEXT COMMENT '反馈内容',
MODIFY COLUMN `rating` INT COMMENT '评分';

-- 8. categories 表注释
ALTER TABLE `categories` COMMENT = '图片分类表';

-- categories 表字段注释
ALTER TABLE `categories`
MODIFY COLUMN `id` CHAR(36) PRIMARY KEY DEFAULT (UUID()) COMMENT '分类UUID',
MODIFY COLUMN `user_id` VARCHAR(255) NOT NULL COMMENT '用户ID',
MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '分类名称',
MODIFY COLUMN `color` VARCHAR(20) DEFAULT 'blue' COMMENT '分类颜色',
MODIFY COLUMN `sort_order` INT DEFAULT 0 COMMENT '排序顺序',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- 9. images 表注释
ALTER TABLE `images` COMMENT = '图片信息表';

-- images 表字段注释
ALTER TABLE `images`
MODIFY COLUMN `id` CHAR(36) PRIMARY KEY DEFAULT (UUID()) COMMENT '图片UUID',
MODIFY COLUMN `user_id` VARCHAR(255) NOT NULL COMMENT '用户ID',
MODIFY COLUMN `file_url` TEXT NOT NULL COMMENT '文件URL',
MODIFY COLUMN `thumbnail_url` TEXT NOT NULL COMMENT '缩略图URL',
MODIFY COLUMN `name` VARCHAR(255) NOT NULL COMMENT '图片名称',
MODIFY COLUMN `category_id` CHAR(36) COMMENT '分类ID',
MODIFY COLUMN `file_size` INT COMMENT '文件大小(字节)',
MODIFY COLUMN `mime_type` VARCHAR(100) COMMENT 'MIME类型',
MODIFY COLUMN `width` INT COMMENT '图片宽度',
MODIFY COLUMN `height` INT COMMENT '图片高度',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- 10. email_verification_codes 表注释
ALTER TABLE `email_verification_codes` COMMENT = '邮箱验证码表';

-- email_verification_codes 表字段注释
ALTER TABLE `email_verification_codes`
MODIFY COLUMN `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '验证码自增ID',
MODIFY COLUMN `email` VARCHAR(255) NOT NULL COMMENT '邮箱地址',
MODIFY COLUMN `code` VARCHAR(6) NOT NULL COMMENT '验证码',
MODIFY COLUMN `expires_at` DATETIME NOT NULL COMMENT '过期时间',
MODIFY COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
MODIFY COLUMN `is_used` BOOLEAN DEFAULT FALSE COMMENT '是否已使用';

-- 完成提示
SELECT '✅ 所有表和字段的中文注释已添加完成！' AS message;